### PR TITLE
Fix #9

### LINKED ISSUE #9: Dates are currently not parsed correctly
Only years are read into the table struct. 
We need to cast the dates to unix timestamps to make be able to save them as int

### PR DESCRIPTION
**Pull request by MariusDanner**

### CODE REVIEW

**Comment by ramboldio** [comment]
´´´terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check: __n (which is 0) >= this->size() (which is 0)
[1]    16108 abort (core dumped)  ./Main

**Comment by ramboldio** [comment]
```
➜  src git:(issue/#9) ✗ ./Main 
reading csv: Execution Time: 85 ms
reading csv: Execution Time: 4 ms
terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check: __n (which is 0) >= this->size() (which is 0)
[1]    16108 abort (core dumped)  ./Main
```

Got an error when running. The stopwatch measurement output would suggest that the import was successful, but down the line sth broke. Commenting out the print for the date columns didn't work for me. Can you reproduce that issues?

**Comment by MariusDanner** [comment]
Ah ok, I see.
I think the issue arises because you are filtering by a year. The date is stored as a unix timestamp now. I am going to fix that.

**Comment by ramboldio** [comment]
Awesome, now it works. :grin: :+1:

**Review by ramboldio — APPROVED** [review]
Outstanding!

**Pull request merged**
